"""PHASE_775 lock audit (lean-expert): no-message plants with WITHIN-FOLIO non-stationarity, and keyed ciphers whose
hidden stream has line- or paragraph-level clustering but no word order. Controls only: B's real token lines are
never scored (B supplies its skeleton and the adjacent-pair tables of habit3, the phase's declared exposure).

Question: can a process with no keyed message, or a keyed process with no word order, reach the PRESENT bar
(G_K >= tau_K) when its structure varies within a folio at the line or paragraph level? The header-aware EF null
permutes within folio x line type, so any line- or paragraph-level clustering is destroyed by the null and enters dS.

Plants (all in B's skeleton):
  TEMP-u   habit3 with sampling probabilities ~ count^beta; beta drawn per unit u (line or paragraph) from {lo, hi}
  SECMIX-u habit3 fitted per section; each unit u is generated by the chain of a section drawn at random
           (weights = B's line counts per section), so lines of one folio come from different chains
  EDIAL-u  habit3 output, then a per-unit e-dial: mode 1 lengthens one e-run (if the longer form exists in B's
           vocabulary), mode 0 shortens one (if the shorter form exists), each with probability q
  KTWIN-u  context-keyed cipher (true key K1 or K2) of a plaintext segment whose words are shuffled within each unit u
           (line or paragraph): unit composition kept, word order destroyed
  KEY      the ordinary keyed cipher of the same segment (reference)

Every corpus is scored with the phase's own pipeline (key775.Decoder, ef774.Corpus with the phase's EF groups and the
same RNG use as key775.run, so the lag-1 numbers equal key775.run's), plus a lag-2 version of S on the same samples.

Usage: python audit_plants775.py [workers<=4]
"""
import json
import os
import sys
import time
from collections import Counter, defaultdict
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
PH = HERE.parent
OUT = PH.parent / 'results' / 'audit'
R = 200


def _setup():
    os.environ['NUMBA_CACHE_DIR'] = str(PH / '__pycache__' / 'numba')
    for v in ('OMP_NUM_THREADS', 'OPENBLAS_NUM_THREADS', 'MKL_NUM_THREADS'):
        os.environ[v] = '1'
    try:
        import psutil
        psutil.Process().nice(psutil.IDLE_PRIORITY_CLASS)
    except Exception:
        pass
    sys.path.insert(0, str(PH))


# ------------------------------------------------------------------------------------------------ habit3 tables
class H3:
    """habit3's tables (hr768.habit3_lines) with a temperature on the sampling probabilities."""

    def __init__(self, lines, tc, GL, min_tok_ctx=20, min_joint_ctx=5):
        self.tc, self.GL = tc, GL
        self.initial, self.uni = Counter(), Counter()
        self.ctxT, self.ctx2, self.ctx1 = defaultdict(Counter), defaultdict(Counter), defaultdict(Counter)
        for ln in lines:
            prev = None
            for w in ln:
                if w is None:
                    prev = None
                    continue
                self.uni[w] += 1
                if prev is None:
                    self.initial[w] += 1
                else:
                    self.ctxT[prev][w] += 1
                    self.ctx2[(tc(prev), GL.findall(prev)[-1])][w] += 1
                    self.ctx1[tc(prev)][w] += 1
                prev = w
        self.nT = {k: sum(v.values()) for k, v in self.ctxT.items()}
        self.n2 = {k: sum(v.values()) for k, v in self.ctx2.items()}
        self.mt, self.mj = min_tok_ctx, min_joint_ctx
        self.cache = {}

    def table(self, prev):
        if prev is None:
            return ('init',), self.initial
        if self.nT.get(prev, 0) >= self.mt:
            return ('T', prev), self.ctxT[prev]
        j = (self.tc(prev), self.GL.findall(prev)[-1])
        if self.n2.get(j, 0) >= self.mj:
            return ('J',) + j, self.ctx2[j]
        c1 = self.ctx1.get(self.tc(prev))
        if c1:
            return ('C', self.tc(prev)), c1
        return ('uni',), self.uni

    def draw(self, prev, beta, rng):
        key, counter = self.table(prev)
        ck = (key, beta)
        if ck not in self.cache:
            keys = list(counter)
            p = np.array([counter[k] for k in keys], dtype=float) ** beta
            self.cache[ck] = (keys, np.cumsum(p / p.sum()))
        keys, cum = self.cache[ck]
        return keys[min(int(np.searchsorted(cum, rng.random())), len(keys) - 1)]


def units_of(sk, lt, mode):
    """Unit id per line: 'line' = the line; 'para' = paragraph (a paragraph-first line or a new folio starts one)."""
    if mode == 'line':
        return list(range(len(sk['lines'])))
    out, u, prevf = [], -1, None
    for f, t in zip(sk['folios'], lt):
        if t == 'H' or f != prevf:
            u += 1
        out.append(u)
        prevf = f
    return out


def generate(sk, unit, tables, betas, rng):
    out = []
    for li, ln in enumerate(sk['lines']):
        T, b = tables[unit[li]], betas[unit[li]]
        prev, cur = None, []
        for w in ln:
            if w is None:
                cur.append(None)
                prev = None
                continue
            t = T.draw(prev, b, rng)
            cur.append(t)
            prev = t
        out.append(cur)
    return out


def edial(lines, sk, unit, q, rng, vocab):
    import re
    er = re.compile(r'e+')
    mode = {u: int(rng.integers(2)) for u in set(unit)}
    out = []
    for li, ln in enumerate(lines):
        m = mode[unit[li]]
        cur = []
        for w in ln:
            if w is None or rng.random() >= q:
                cur.append(w)
                continue
            runs = list(er.finditer(w))
            cand = []
            for r in runs:
                a, b = r.span()
                if m == 1:
                    v = w[:b] + 'e' + w[b:]
                elif b - a >= 2:
                    v = w[:a] + w[a + 1:]
                else:
                    continue
                if v in vocab:
                    cand.append(v)
            cur.append(cand[int(rng.integers(len(cand)))] if cand else w)
        out.append(cur)
    return out


def shuffle_within(stream, sk, unit, seed):
    rng = np.random.default_rng(seed)
    out = list(stream)
    by = defaultdict(list)
    i = 0
    for li, ln in enumerate(sk['lines']):
        for w in ln:
            if w is not None:
                by[unit[li]].append(i)
                i += 1
    for idx in by.values():
        vals = [out[j] for j in idx]
        rng.shuffle(vals)
        for j, v in zip(idx, vals):
            out[j] = v
    return out


# ------------------------------------------------------------------------------------------------ scoring
def score(lines, groups, seed):
    """key775.run's lag-1 results (identical RNG use) plus lag-2 S and G on the same EF samples."""
    import key775 as K
    E = K.E
    rng = np.random.default_rng(seed)
    C = E.Corpus(lines, groups, sig=E.sig_fl2, ns=(2,))
    Ds = {k: K.Decoder(C, k) for k in ('K0', 'K1', 'K2')}
    lo = C.line_of
    pair2 = np.flatnonzero(lo[2:] == lo[:-2]) + 2
    pair1 = Ds['K0'].pair

    def mi(r, idx, lag):
        a, b = r[idx - lag], r[idx]
        ok = (a > 0) & (b > 0)
        a, b = a[ok], b[ok]
        Kk = K.R_MAX + 1
        j = np.bincount(a * Kk + b, minlength=Kk * Kk).reshape(Kk, Kk).astype(float)
        n = j.sum()
        pa, pb, pj = j.sum(1) / n, j.sum(0) / n, j / n
        nz = pj > 0
        return float((pj[nz] * np.log2(pj[nz] / np.outer(pa, pb)[nz])).sum())

    def both(D, tok):
        r = D.decode(tok)
        return mi(r, pair1, 1), mi(r, pair2, 2)
    obs1, obs2 = {}, {}
    for k, D in Ds.items():
        obs1[k], obs2[k] = both(D, C.tok)
        assert abs(obs1[k] - D.stat(C.tok)) < 1e-12
    n1, n2 = {k: [] for k in Ds}, {k: [] for k in Ds}
    for _ in range(R):
        t = C.sample(rng)
        for k, D in Ds.items():
            a, b = both(D, t)
            n1[k].append(a)
            n2[k].append(b)
    out = {}
    for lag, obs, nul in (('lag1', obs1, n1), ('lag2', obs2, n2)):
        v0 = np.array(nul['K0'])
        d = {'dS_K0': obs['K0'] - float(v0.mean())}
        for k in ('K1', 'K2'):
            gv = np.array(nul[k]) - v0
            g = obs[k] - obs['K0']
            d[f'dS_{k}'] = obs[k] - float(np.mean(nul[k]))
            d[f'G_{k}'] = g - float(gv.mean())
            d[f'p_{k}'] = float((1 + (gv >= g).sum()) / (1 + R))
        out[lag] = d
    return out


def specs():
    S = []
    for mode in ('line', 'para'):
        for lo_, hi_ in ((0.5, 2.0), (0.7, 1.4)):
            for s in range(2):
                S.append(('TEMP', mode, (lo_, hi_), None, 775100 + 10 * s + int(10 * lo_)))
        for s in range(2):
            S.append(('SECMIX', mode, None, None, 775200 + 10 * s + (mode == 'para')))
        for q in (1.0, 0.5):
            S.append(('EDIAL', mode, q, None, 775300 + int(10 * q) + (mode == 'para')))
    for pt in (('NT_la', 0), ('NT_it', 0), ('LAT_rec', 0), ('ITA_dante', 0)):
        for key in (1, 2):
            S.append(('KEY', None, key, pt, 775400 + key))
            for mode in ('line', 'para'):
                S.append(('KTWIN', mode, key, pt, 775500 + key + 10 * (mode == 'para')))
    S.append(('HABIT3', None, None, None, 775600))
    return S


def run_one(spec):
    _setup()
    import gen775 as GK
    G = GK.G
    HR = G.HR
    kind, mode, par, pt, seed = spec
    t0 = time.time()
    sk = HR.b_skeleton()
    lt = GK.b_line_types(sk)
    rng = np.random.default_rng(seed)
    info = {}
    if kind in ('TEMP', 'SECMIX', 'EDIAL', 'HABIT3'):
        unit = units_of(sk, lt, mode or 'line')
        base = H3(sk['lines'], HR.token_class, HR.GLYPH_RE)
        nu = max(unit) + 1
        if kind == 'TEMP':
            lo_, hi_ = par
            betas = [lo_ if rng.random() < 0.5 else hi_ for _ in range(nu)]
            lines = generate(sk, unit, [base] * nu, betas, rng)
        elif kind == 'SECMIX':
            secs = sorted(set(sk['sections']))
            tabs = {s: H3([ln for ln, x in zip(sk['lines'], sk['sections']) if x == s], HR.token_class, HR.GLYPH_RE)
                    for s in secs}
            w = np.array([sk['sections'].count(s) for s in secs], dtype=float)
            pick = [secs[int(rng.choice(len(secs), p=w / w.sum()))] for _ in range(nu)]
            lines = generate(sk, unit, [tabs[s] for s in pick], [1.0] * nu, rng)
        elif kind == 'EDIAL':
            lines = generate(sk, unit, [base] * nu, [1.0] * nu, rng)
            vocab = set(base.uni)
            lines = edial(lines, sk, unit, par, rng, vocab)
        else:
            lines = generate(sk, unit, [base] * nu, [1.0] * nu, rng)
    else:
        words = G.plaintext_words(pt[0])
        stream = G.segment_stream(words, sk, pt[1])
        if kind == 'KTWIN':
            stream = shuffle_within(stream, sk, units_of(sk, lt, mode), seed + 1)
        lines = GK.keyed_cipher(stream, sk, par, seed)
        info['O'] = GK.plaintext_order_index(stream, sk)
    assert lines != sk['lines'], 'refusing to score B'
    res = score(lines, GK.ef_groups(sk), seed)
    name = '|'.join(str(x) for x in spec)
    ntypes = len({w for ln in lines for w in ln if w is not None})
    return name, {'spec': [str(x) for x in spec], 'types': ntypes, **info, 'res': res, 'runtime_s': time.time() - t0}


def main():
    workers = min(4, int(sys.argv[1]) if len(sys.argv) > 1 else 4)
    _setup()
    OUT.mkdir(parents=True, exist_ok=True)
    TH = json.load(open(PH.parent / 'results' / 'thresholds775.json', encoding='utf-8'))
    fn = OUT / 'audit_plants775.json'
    logf = open(OUT / 'audit_plants775_log.txt', 'w', encoding='utf-8')

    def log(m):
        print(m, flush=True)
        logf.write(m + '\n')
        logf.flush()
    log(f'tau_K1 {TH["tau_K1"]:.5f}  tau_K2 {TH["tau_K2"]:.5f}  R {R}')
    out = {}
    T0 = time.time()
    with ProcessPoolExecutor(max_workers=workers) as ex:
        futs = {ex.submit(run_one, s): s for s in specs()}
        for f in as_completed(futs):
            try:
                name, r = f.result()
            except Exception as e:  # noqa: BLE001
                log(f'FAILED {futs[f]}: {e!r}')
                continue
            out[name] = r
            a, b = r['res']['lag1'], r['res']['lag2']
            log(f'[{time.time() - T0:6.0f}s] {name:44s} O {r.get("O", float("nan")):.3f} | lag1 dS0 {a["dS_K0"]:+.4f} '
                f'G1 {a["G_K1"]:+.4f} p {a["p_K1"]:.3f} G2 {a["G_K2"]:+.4f} p {a["p_K2"]:.3f} | lag2 dS0 '
                f'{b["dS_K0"]:+.4f} G1 {b["G_K1"]:+.4f} G2 {b["G_K2"]:+.4f}')
            json.dump(out, open(fn, 'w'), indent=1)
    log('done')


if __name__ == '__main__':
    main()
