"""
Build a complete cold read .md from:
1. A recipe header file (hand-written per folio)
2. Generated workshop tables
3. Decode summary JSON
4. A cross-paragraph + verdict section (hand-written per folio)

Usage: python build_cold_read.py <folio>

Expects:
- results/data/{folio}_workshop_tables.md (generated by compose_workshop_readings.py)
- results/data/{folio}_decode_summary.json
- results/headers/{folio}_header.md (recipe, predictions, overview — hand-written)
- results/footers/{folio}_footer.md (cross-paragraph patterns, verdict — hand-written)

Outputs:
- results/cold_reads/{folio}_cold_read.md
"""
import json, sys, re, os

folio = sys.argv[1] if len(sys.argv) > 1 else 'f75r'
base = 'phases/PHASE_668_F76R_COLD_READ/results'

tables_path = f'{base}/data/{folio}_workshop_tables.md'
json_path = f'{base}/data/{folio}_decode_summary.json'
header_path = f'{base}/headers/{folio}_header.md'
footer_path = f'{base}/footers/{folio}_footer.md'
output_path = f'{base}/cold_reads/{folio}_cold_read.md'

with open(tables_path, encoding='utf-8') as f:
    tables_text = f.read()

with open(json_path, encoding='utf-8') as f:
    summary = json.load(f)

with open(header_path, encoding='utf-8') as f:
    header = f.read()

with open(footer_path, encoding='utf-8') as f:
    footer = f.read()

# Parse tables into per-paragraph groups
paragraphs = summary['paragraphs']
table_lines = tables_text.split('\n')

para_tables = {p['paragraph']: [] for p in paragraphs}

# Figure out which lines belong to which paragraph
line_to_para = {}
for p in paragraphs:
    line_range = p['lines']
    if '-' in line_range:
        start, end = line_range.split('-')
        for ln in range(int(start), int(end) + 1):
            line_to_para[ln] = p['paragraph']
    else:
        line_to_para[int(line_range)] = p['paragraph']

current_para = None
for tl in table_lines:
    m = re.match(r'\*\*L(\d+)', tl)
    if m:
        lnum = int(m.group(1))
        current_para = line_to_para.get(lnum)
    if current_para is not None:
        para_tables[current_para].append(tl)

# Build structural profile for each paragraph
def build_profile(p):
    lines_str = p['lines']
    n = p['n_tokens']
    total = sum(pp['n_tokens'] for pp in paragraphs)
    pct = 100 * n // total

    pfx = p['prefix_counts']
    total_pfx = sum(pfx.values())
    none_count = pfx.get('none', 0)
    recognized = total_pfx - none_count

    # Count unrecognized from tables
    ptables = '\n'.join(para_tables.get(p['paragraph'], []))
    unrec = ptables.count('unrecognized') + ptables.count('bare token')

    out = []
    out.append(f'| Feature | Value |')
    out.append(f'|---------|-------|')
    out.append(f'| Tokens | {n} ({pct}% of folio) |')
    out.append(f'| e-depth | {p["mean_e_depth"]:.3f} |')
    out.append(f'| dar count | {p["dar_count"]} |')
    out.append(f'| Quality checks (chek/shek) | {p["chekar_count"]} |')

    obs = p.get('obs_middle_counts', {})
    if obs:
        obs_str = ', '.join(f'{k}x{v}' for k, v in obs.items())
    else:
        obs_str = 'none'
    out.append(f'| Observation MIDDLEs | {obs_str} |')
    out.append(f'| hh (extended obs) | {p["hh_count"]} |')

    # Top prefixes
    out.append('')
    out.append('**Top prefixes:**')
    sorted_pfx = sorted(pfx.items(), key=lambda x: -x[1])
    for name, count in sorted_pfx[:8]:
        if name == 'none':
            continue
        pct_pfx = 100 * count // total_pfx
        out.append(f'- {name}: {count} ({pct_pfx}%)')

    return '\n'.join(out)

# Assemble
output = []
output.append(header.rstrip())
output.append('\n\n')

for p in paragraphs:
    pnum = p['paragraph']
    lines_str = p['lines']
    n = p['n_tokens']

    output.append(f'---\n\n')
    output.append(f'## Paragraph {pnum}: Lines {lines_str} ({n} tokens)\n\n')
    output.append(f'### Token Reading (v2 workshop readings)\n\n')
    output.append(f'Every token on every line. **B Dict** = B Operational Dictionary, **Comp-v2** = composed from atoms, **---** = truly unrecognized.\n\n')

    # Tables
    table_content = '\n'.join(para_tables.get(pnum, []))
    output.append(table_content)
    output.append('\n\n')

    # Structural profile
    output.append(f'### P{pnum} Structural Profile\n\n')
    output.append(build_profile(p))
    output.append('\n\n')

output.append('---\n\n')
output.append(footer.rstrip())
output.append('\n')

with open(output_path, 'w', encoding='utf-8') as f:
    f.write(''.join(output))

total_tokens = sum(p['n_tokens'] for p in paragraphs)
print(f'Built {output_path}')
print(f'Total tokens: {total_tokens}')
print(f'Paragraphs: {len(paragraphs)}')
