#!/usr/bin/env python3
"""Update folio_viewer.py to use the new character mapping."""
import re

# Read current file
with open('vee/app/ui/folio_viewer.py', 'r', encoding='utf-8') as f:
    content = f.read()

# 1. Add json import after re import
content = content.replace(
    'import re\n\nfrom PyQt5',
    'import re\nimport json\n\nfrom PyQt5'
)

# 2. Replace the EVA_TO_FONT_MAP section with code that loads from JSON
old_map = '''# EVA-to-font character remapping
# The font uses different character positions than EVA standard
# EVA letter -> font letter that displays the correct glyph
EVA_TO_FONT_MAP = {
    'h': 'k',  # EVA h (pos 8) displays as font k (pos 11)
    'g': 'p',  # EVA g (pos 7) displays as font p (pos 16)
    # Add more mappings as identified
}'''

new_map = '''# Load character mapping from our encoding to EVA font
# Generated by comparing our transcription against official ZL transcription
def _load_font_mapping():
    """Load the character mapping from JSON file."""
    mapping_paths = [
        Path(__file__).parent.parent / "eva_font_mapping.json",
        Path("C:/git/voynich/vee/app/eva_font_mapping.json"),
    ]
    for path in mapping_paths:
        if path.exists():
            with open(path, 'r') as f:
                return json.load(f)
    return {}

EVA_TO_FONT_MAP = _load_font_mapping()'''

content = content.replace(old_map, new_map)

# 3. Update the glyph mapping logic in _create_line_widget
old_logic = '''        if self._use_glyphs:
            # Clean text for Voynich font: keep letters and digits (bench chars)
            # Remove special chars but keep letters and digits
            clean_text = re.sub(r'[^a-zA-Z0-9.\s]', '', line.text).lower()
            # Map bench characters (digits) to extended Voynich glyphs at U+F0xx
            mapped_text = ''.join(EVA_BENCH_CHAR_MAP.get(c, c) for c in clean_text)
            display_text = mapped_text'''

new_logic = '''        if self._use_glyphs:
            # Apply character mapping from our encoding to EVA font
            # First map our characters to EVA equivalents, then to font
            mapped_chars = []
            for c in line.text:
                if c in '.\n\r':
                    mapped_chars.append(c)
                elif c in EVA_TO_FONT_MAP:
                    mapped_chars.append(EVA_TO_FONT_MAP[c])
                elif c.lower() in EVA_TO_FONT_MAP:
                    mapped_chars.append(EVA_TO_FONT_MAP[c.lower()])
                elif c.isalpha():
                    mapped_chars.append(c.lower())
                # Skip other characters (punctuation, etc.)
            display_text = ''.join(mapped_chars)'''

content = content.replace(old_logic, new_logic)

# Write updated file
with open('vee/app/ui/folio_viewer.py', 'w', encoding='utf-8') as f:
    f.write(content)

print("Updated folio_viewer.py successfully")
